# Snakemake pipeline for single-cell data
rule all:
    input:
        "res/ucla_integrated.rds",
        "res/ucla_clustered.rds",
        "res/ucla_cluster_markers.tsv"

rule qc_preprocessing:
    input:
        matrix_dir = "data/input/filtered_feature_bc_matrix",
        aggr_csv = "data/internal/aggregation_1.csv"
    output:
        output = "res/ucla_qc_filtered.rds"
    script:
        "run_qc.R"

rule normalize_and_integrate:
    input:
        "res/ucla_qc_filtered.rds"
    output:
        "res/ucla_integrated.rds"
    script:
        "run_normalize_and_integrate.R"

rule cluster_and_markers:
    input:
        "res/ucla_integrated.rds"
    output:
        clustered = "res/ucla_clustered.rds",
        markers = "res/ucla_cluster_markers.tsv"
    script:
        "run_cluster_and_markers.R"

rule score_signatures:
    input:
        "res/ucla_clustered.rds"
    output:
        "res/ucla_clustered_with_signatures.rds"
    script:
        "run_score_signatures.R"

rule infer_pseudotime:
    input:
        "res/ucla_integrated.rds"
    output:
        rds = "res/ucla_monocle_pseudotime.rds",
        plot = "res/ucla_monocle_pseudotime.pdf"
    script:
        "workflows/singlecell/run_infer_pseudotime.R"